apiVersion: v1
kind: Namespace
metadata:
  name: c2c-order-flow-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-order-flow-deployment
  namespace: c2c-order-flow-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/c2c:0440c83629916f4b3f189c9fa632445e5a110e84

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-order-flow-label
  name: c2c-order-flow-service
  namespace: c2c-order-flow-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---